# Generated by Django 4.2.7 on 2024-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry_data',
            name='answer',
            field=models.TextField(blank=True, default=1, verbose_name='回答'),
            preserve_default=False,
        ),
    ]
