# Generated by Django 4.2.7 on 2024-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pop_up1',
            field=models.CharField(blank=True, verbose_name='ポップアップ1'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up2',
            field=models.CharField(blank=True, verbose_name='ポップアップ2'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up3',
            field=models.CharField(blank=True, verbose_name='ポップアップ3'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up4',
            field=models.CharField(blank=True, verbose_name='ポップアップ4'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up5',
            field=models.CharField(blank=True, verbose_name='ポップアップ5'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up_id1',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID1'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up_id2',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID2'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up_id3',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID3'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up_id4',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID4'),
        ),
        migrations.AddField(
            model_name='member',
            name='pop_up_id5',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID5'),
        ),
    ]
