# Generated by Django 4.2.7 on 2024-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='follow',
            field=models.BooleanField(null=True, verbose_name='フォローON/OFF'),
        ),
        migrations.AlterField(
            model_name='business_time_graph',
            name='break_change',
            field=models.BooleanField(null=True, verbose_name='休憩変更チェック'),
        ),
    ]
