# Generated by Django 4.2.7 on 2024-05-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0002_member_pop_up1_member_pop_up2_member_pop_up3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_time_graph',
            name='break_change',
            field=models.BooleanField(null=True, verbose_name='工数入力OK_NG'),
        ),
    ]
