# Generated by Django 4.2.7 on 2024-04-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0002_alter_inquiry_data_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator_data',
            name='backup_file',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_A1',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_A2',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_P',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_R',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_T1',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_T2',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_W1',
        ),
        migrations.RemoveField(
            model_name='administrator_data',
            name='file_location_W2',
        ),
    ]
