# Generated by Django 4.2.7 on 2024-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0002_team_member_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='member11',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='メンバー従業員番号11'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='member12',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='メンバー従業員番号12'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='member13',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='メンバー従業員番号13'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='member14',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='メンバー従業員番号14'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='member15',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='メンバー従業員番号15'),
        ),
    ]
