# Generated by Django 4.2.7 on 2024-04-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0002_alter_administrator_data_menu_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_time_graph',
            old_name='def_Ver2',
            new_name='def_ver2',
        ),
        migrations.RenameField(
            model_name='business_time_graph',
            old_name='employee_No3',
            new_name='employee_no3',
        ),
    ]
