# Generated by Django 4.2.7 on 2024-04-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0003_rename_def_ver2_business_time_graph_def_ver2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry_data',
            old_name='employee_No2',
            new_name='employee_no2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='employee_No',
            new_name='employee_no',
        ),
        migrations.RenameField(
            model_name='team_member',
            old_name='employee_No5',
            new_name='employee_no5',
        ),
    ]
