# Generated by Django 4.2.7 on 2024-09-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0003_team_member_member11_team_member_member12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shop',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R'), ('W1', 'W1'), ('W2', 'W2'), ('T1', 'T1'), ('T2', 'T2'), ('A1', 'A1'), ('A2', 'A2'), ('その他', 'その他'), ('組長以上(P,R,T,その他)', '組長以上(P,R,T,その他)'), ('組長以上(W,A)', '組長以上(W,A)')], max_length=15, verbose_name='ショップ'),
        ),
    ]
