# Generated by Django 4.2.7 on 2024-05-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0003_business_time_graph_break_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='break_time1',
            field=models.CharField(max_length=9, verbose_name='1直昼休憩時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time1_over1',
            field=models.CharField(max_length=9, verbose_name='1直残業休憩時間1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time1_over2',
            field=models.CharField(max_length=9, verbose_name='1直残業休憩時間2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time1_over3',
            field=models.CharField(max_length=9, verbose_name='1直残業休憩時間3'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time2',
            field=models.CharField(max_length=9, verbose_name='2直昼休憩時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time2_over1',
            field=models.CharField(max_length=9, verbose_name='2直残業休憩時間1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time2_over2',
            field=models.CharField(max_length=9, verbose_name='2直残業休憩時間2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time2_over3',
            field=models.CharField(max_length=9, verbose_name='2直残業休憩時間3'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time3',
            field=models.CharField(max_length=9, verbose_name='3直昼休憩時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time3_over1',
            field=models.CharField(max_length=9, verbose_name='3直残業休憩時間1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time3_over2',
            field=models.CharField(max_length=9, verbose_name='3直残業休憩時間2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time3_over3',
            field=models.CharField(max_length=9, verbose_name='3直残業休憩時間3'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time4',
            field=models.CharField(max_length=9, verbose_name='常昼昼休憩時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time4_over1',
            field=models.CharField(max_length=9, verbose_name='常昼残業休憩時間1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time4_over2',
            field=models.CharField(max_length=9, verbose_name='常昼残業休憩時間2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='break_time4_over3',
            field=models.CharField(max_length=9, verbose_name='常昼残業休憩時間3'),
        ),
    ]
