# Generated by Django 4.2.7 on 2024-05-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0004_alter_member_break_time1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_time_graph',
            name='breaktime',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='昼休憩時間'),
        ),
        migrations.AlterField(
            model_name='business_time_graph',
            name='breaktime_over1',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='残業休憩時間1'),
        ),
        migrations.AlterField(
            model_name='business_time_graph',
            name='breaktime_over2',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='残業休憩時間2'),
        ),
        migrations.AlterField(
            model_name='business_time_graph',
            name='breaktime_over3',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='残業休憩時間3'),
        ),
    ]
