# Generated by Django 4.2.7 on 2024-04-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0004_rename_employee_no2_inquiry_data_employee_no2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_time_graph',
            name='completion',
        ),
    ]
