# Generated by Django 4.2.7 on 2024-11-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0004_alter_member_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='break_check',
            field=models.BooleanField(null=True, verbose_name='休憩エラー有効チェック'),
        ),
    ]
