# Generated by Django 4.2.7 on 2024-05-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0005_alter_business_time_graph_breaktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_time_graph',
            name='def_ver2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工数区分定義Ver'),
        ),
    ]
