# Generated by Django 4.2.7 on 2024-05-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0001_initial_squashed_0005_remove_business_time_graph_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry_data',
            name='content_choice',
            field=models.CharField(choices=[('要望', '要望'), ('不具合', '不具合'), ('問い合わせ', '問い合わせ')], max_length=5, verbose_name='内容選択'),
        ),
    ]
