# Generated by Django 4.2.7 on 2024-05-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0006_alter_business_time_graph_def_ver2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_time_graph',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kosu.member', verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='inquiry_data',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='inquiry_data',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kosu.member', verbose_name='氏名'),
        ),
    ]
