# Generated by Django 4.2.7 on 2024-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0006_alter_business_time_graph_def_ver2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry_data',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
    ]
