# Generated by Django 4.2.7 on 2024-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0006_alter_inquiry_data_content_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_data',
            name='administrator_employee_no1',
            field=models.IntegerField(blank=True, null=True, verbose_name='問い合わせ担当者従業員番号1'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='administrator_employee_no2',
            field=models.IntegerField(blank=True, null=True, verbose_name='問い合わせ担当者従業員番号2'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='administrator_employee_no3',
            field=models.IntegerField(blank=True, null=True, verbose_name='問い合わせ担当者従業員番号3'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up1',
            field=models.TextField(blank=True, verbose_name='ポップアップ1'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up2',
            field=models.TextField(blank=True, verbose_name='ポップアップ2'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up3',
            field=models.TextField(blank=True, verbose_name='ポップアップ3'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up4',
            field=models.TextField(blank=True, verbose_name='ポップアップ4'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up5',
            field=models.TextField(blank=True, verbose_name='ポップアップ5'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up_id1',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポップアップID1'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up_id2',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポップアップID2'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up_id3',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポップアップID3'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up_id4',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポップアップID4'),
        ),
        migrations.AddField(
            model_name='administrator_data',
            name='pop_up_id5',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポップアップID5'),
        ),
    ]
