# Generated by Django 4.2.7 on 2024-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0007_administrator_data_administrator_employee_no1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_data',
            name='administrator_employee_no1',
            field=models.CharField(blank=True, null=True, verbose_name='問い合わせ担当者従業員番号1'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='administrator_employee_no2',
            field=models.CharField(blank=True, null=True, verbose_name='問い合わせ担当者従業員番号2'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='administrator_employee_no3',
            field=models.CharField(blank=True, null=True, verbose_name='問い合わせ担当者従業員番号3'),
        ),
    ]
