# Generated by Django 4.2.7 on 2024-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0008_alter_administrator_data_administrator_employee_no1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up1',
            field=models.CharField(blank=True, verbose_name='ポップアップ1'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up2',
            field=models.CharField(blank=True, verbose_name='ポップアップ2'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up3',
            field=models.CharField(blank=True, verbose_name='ポップアップ3'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up4',
            field=models.CharField(blank=True, verbose_name='ポップアップ4'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up5',
            field=models.CharField(blank=True, verbose_name='ポップアップ5'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up_id1',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID1'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up_id2',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID2'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up_id3',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID3'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up_id4',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID4'),
        ),
        migrations.AlterField(
            model_name='administrator_data',
            name='pop_up_id5',
            field=models.CharField(blank=True, null=True, verbose_name='ポップアップID5'),
        ),
    ]
